var quote_list = [
"My shadow is the best friend of mine!",
"In the world nobody is smarter than anybody, because the one you think fooler than you may surely know something that you don\'t.",
"Sometimes you realize that the ones you thought you know the most are actually the ones you know at all.",
"Think twice before getting in a relationship because once you\'re in is not so easy to get out!",
"You\'ve made me such beautiful scars that I will never need a tattoo!",
"I\'d rather live alone in madness than surrounded by people that I don\'t even know.",
"Maybe there\'s nothing worth risking your life for, but there are times when you just have to.",
"Every time I miss you a star is falling, so when you\'ll look at the sky, and will see it devoid of stars, you\'ll know it\'s because you made me miss you, for too long.",
"I\'m so hot by you right now that you cannot ever even imagine!",
"I don\'t see worth changing an unfunny loving man for three joking bullshits talking guys but never mind it in the world are many human minds and mentalities and at least one of them will agree me!",
"Freedom sucks when you don\'t have with who to share it!",
"There\'s no way begging for forgiveness and to be forgiven, no you have to break every part in your body for hoping another second chance!",
"For everything you do in this life you\'ll be getting a reward, good or bad, it\'s just depending on what you do.",
"Scars are better than tattoos because it will remind you the mistakes that you have done in the distant past.",
"My life is written in the scars, so it is with my devotion for you.",
"In the world surely is somebody who could make you forget all your problems, but it\'s just hard work to find it.",
"Sometimes you just can\'t believe the things that are happening to you!",
"You all were laughing on me because I were too small in your eyes but blink now and see how big I am comparing to you.",
"I\'m not the only one who should burn in hell, you should take my hand while doing it.",
"There is no love without a tear but sometimes your tears are falling for nothing because there is no love for you from the one you care about.",
"You\'ll never get what you like, you\'ll always get what it comes to you.",
"At the beggining of your life you should get used for being mocked of any fool around you, because all your life you\'ll just find enough people like this.",
"To forgive it\'s a hard thing when you don\'t have any heart beating in your chest!",
"You think you\'re so smart but that won\'t help you see the light when your ego stands in the way.",
"Don\'t start a fire that you can\'t handle, because one day it may simply burn you down!",
"You\'ve been taking care of your body most of the day, now I see why because it\'s the only thing worth in you.",
"You have to find yourself in the words that you are speaking, because if you don\'t it means you\'re a liar.",
"I could fight with anyone in the world for you, but I doubt that if I\'d win you\'d come back to me!",
"You could remember me someday after all, but that day will not mean anything to any of us!",
"I\'ve never been a believer but there are things in this life that I just simply need to trust.",
"Your heart will return to you one day and will see how many damage you caused while it was gone.",
"You can say that I wasn\'t the one that you\'ve always wanted, but someday you will just see that I\'ve been everything you needed.",
"No one knows me better than you do, so if you say that I\'m a motherfucker I just have to believe it.",
"Someday you\'ll can sleep in the light of my shadow because I\'m going to be a shining person in your life.",
"You won\'t do anything else than going ahead making my life harder, and one day you\'ll just stop looking back seeing nothing, nobody to keep you company, because you left the ones that cared about you behind.",
"I\'m that honest only with you so when I say I would it means I do.",
"There has always been a bridge between me and your heart, and I always had to cross it to get there, sometimes the bridge have been breaking because of my legs that were walking too fast, but sometimes you cut the rope that have been holding the bridge steady, and almost everytime I had to fall down, but now I see that the bridge no longer exists, and there is no way for me to your heart now, and it may be so for forever, and I\'m missing too much the way I\'ve been falling.",
"Sometimes there is no second chance, because there are people that don\'t believe in it to may offer you one.",
"I could wait for you forever but I just know you won\'t come back!",
"There are people in the world that could make you shiver even on the hottest places on the earth.",
"I could just simply look you in the eyes and tell you honestly what I feel, but after I\'d finish the only thing that I\'d hear from you is fuck off.",
"Your soul is cold because in your heart there is no longer any flame to warm it.",
"This world would look better if were not allowed to anyone to have children, because there are people who don\'t know how to raise them.",
"You can do everything you want to change the future, but you can\'t do anything to change the past.",
"You\'ve wounded me because that was the easiest thing to do!",
"I\'ve been busy making my hopes and dreams only to see them tearing apart by the one who were on the top of them.",
"You\'re leaving everything behind hoping that you\'ll never need them again, but in case that you don\'t know life is like a wheel, and if you\'re not planning to die yet, then for sure you\'ll be catching that wheel when it turns up.",
"I just know you won\'t come back but it\'s so hard for me to accept it!",
"I\'m sad when things go wrong, but somehow I find a reason to stay strong, because I know that some of those thing only to me could happen and only I could treat them in the way I do, and that makes me unique.",
"You have to fall if you want to learn to fly!",
"Have you ever thought that a better life for you may mean a worse life for the others, if you don\'t I don\'t mind I know your selfish!",
"A war is lost when there is nothing left to fight for.",
"I\'ve been climbing a mountain for love in this relationship and when I finally reached the top, I\'ve been thrown away as a reward.",
"I could make you proud of me if you\'d have given me the chance!",
"You\'re never too young for being loved, but you can be too young for caring about it.",
"I could build a ladder with the hopes and wishes that I had with you, a ladder that could lead me through the sky up in heaven.",
"I had a good time with you, but now I have to pay for it, so every smile that you brought on my face now is changing into a tear.",
"I\'d go on my feet surrounding the Earth only if I could find someone just like you.",
"You should dig a hole for your body, because a man without a heart beating in his chest is called dead.",
"It\'s harder to fly when you\'re alone, because you know if you\'d fall no one would be there to catch you.",
"It takes only a second for the present to become the past.",
"Deep thinking is a blessing and if you reach that, it will help you stay away from the troubles you may cause.",
"A day will come when I\'ll find the light to guide me through the darkness that you left behind, I just need to believe in that.",
"The best story to tell your children at old age is one that hasn\'t ended yet.",
"A wound may heal in time but the scars will last forever.",
"These bodies are battlefields for our souls.",
"You will never find that person of your dreams, so you\'ll have to change some of those dreams in a way that matches the person you\'ll find, if you want to live in peace with yourself.",
"If after a hill will not follow a valley for sure it will follow a straight path, so once you\'ll get over a problem encountered in this life, if something good won\'t happen to you, don\'t worry you\'ll find at least time to recover and to rest yourself for what\'s next.",
"A sick mind can separate two loving hearts forever.",
"The person that matches you won\'t let you down, and if absurdly will, it will come back to you to apologize and to get you up, even higher than you were before.",
"After every storm the sun will rise, that\'s how it meant to be, and it will be so until the end of time.",
"Now after I\'ve seen how you changed I know I\'m gonna stay in this way forever, I\'m better alone and broken than living a life like yours.",
"Sometimes I think that if I could change my appearance in a way that you wouldn\'t be able to recognize me, I\'d have a change to be with you again.",
"I throw my life away because you made it impossible to live.",
"Be careful for who do you fall, cause if you do it for the wrong person then no one would be there to catch you.",
"Every time before I go to bed, I watch one of your photos and I tell to myself that one day you\'re gonna be mine.",
"Sometimes I need to joke just to not let the world see that I\'m serious in everything I say.",
"A dream is built from hopes and wishes, in the first place, but faith is always the key of their resistance.",
"Denying is the latest fear of letting the truth get shown.",
"Dreaming of someone is a hard thing nowadays, because you can never know how your dream might end.",
"Sometimes you have to get used of the thought that nobody will care about you in the most part of your life.",
"What for you means a little thing for someone else may mean the entire world.",
"Since time has changed you need more courage to live this life than to let it go away.",
"In dreams, no one can follow you, no one can see you, no one can listen to you, that\'s why you\'re so happy \'cause no one can break you off.",
"There are times when you let people down, because you are too weak and they are too heavy, but you don\'t have to go, because once you leave someone behind is probably to never see them again.",
"You can begin to hate people like me cause I started already to hate the ones like you.",
"There are a lot of people with only a purpose on the earth, that is to not let the sun light to reach the ground.",
"Sometimes I have to mask up my words just to hide my true intentions!",
"Sometimes you have to give up on what you love the most for no reason, besides that they are not meant for you.",
"Even if God Himself would tell me that our relationship has ended forever, I still could not believe it.",
"There are tears that will never stop flowing if people\'s hearts won\'t grow up.",
"Not every time it\'s important how it starts, sometimes the essential it\'s just in the way it ends.",
"The greatest stories are written in small steps.",
"Happiness is the art of those who have the most wonderful smiles.",
"It\'s better falling before rising than rising and falling after it.",
"Small things would make the world go round better.",
"Sometimes, you don\'t know what you need, until you got what you want.",
"Love may turn into war when someone wants to quit.",
"I\'m not afraid to die when I got nothing to live for.",
"Life is harder being alone, but sometimes you\'re better on your own.",
"The darkest way of telling goodbye is leaving without giving a try.",
"Why isn\'t the dirt covering me until my breath fades, because I\'m so tired of getting up.",
"Go wherever your heart is, but never turn back where your head was.",
"Say anything you want, but you can\'t change the way I think.",
"Every word that you say brings the storm in my way.",
"I believe I got helped by someone that I never wished to have met.",
"I guess it\'s nothing that I could do to tie my future back on you.",
"Only when the time is right, something will just change your life.",
"Every dream come true is a miracle for the hopeless.",
"Changes on the attitude might become like the weather, sometimes such unpredictable that you may not know if the clouds you see will turn into rain, or simply the wind will blow them away.",
"I think I need you when I breathe to remind me why I live.",
"Everything I need now is all that I got then.",
"Every star knows how to glow in the dark when hope is low.",
"Some people love acting strange, because they hate being normal.",
"It\'s hard to not go crazy when everything you have, becomes everything you\'ve had.",
"Everything I like is stocked into my brain, so even if you push me I\'m going to be the same.",
"A thousand reasons can make you wish the death, but a single one is enough to remind you why to live.",
"Everyone thinks that you\'re alright, because nobody feels the pain you hide.",
"Living without dreams is like walking without eyes, you may never know where you\'re heading without something to guide you.",
"Everything seems a new beginning since you have turned my real meaning.",
"There are things in the world that you could never have, you can only to wish for them.",
"Olderness isn\'t the consequence of time passage, but a brain disease that prepares the soul to leave his body without pain and regrets.",
"Sometimes foolish people fall in love more easily than the smart ones, now you can tell that I\'m a fool, because I know how smart you were.",
"There are times when the past decides what\'s the future\'s all about.",
"You may have the power to make a better world, but without the courage wouldn\'t mean anything.",
"I could live days without water, weeks without food, but nor even an hour without knowing about you.",
"Don\'t be afraid to risk your life for someone who really deserve this, some sacrifices can make your soul worth more than it would by living a thousand years on the earth.",
"I used to be thinking of you, every moment of each day, this is why my mind is empty since you threw my heart away.",
"Sometimes, the best and the worst choices you could make are identical, just because your destiny have to cross that path anyhow.",
"Someday, the sun will shine for you, even when it rains.",
"You may not see who your really friends are, until your enemies stand out.",
"Don\'t let your dreams die and you will live forever.",
"Love without tears is not even friendship.",
"I believe your eyes they are so true, I just can\'t think what they see when you are looking at me.",
"I know some things will never happen but I just like to think of them.",
"The impossibility of escaping your demons is just a reason why you need them to be there.",
"Music sounds even better when you have memories related to it.",
"The shadow that I carry is the matching of friend, and I know that it won\'t leave me, even long after I\'m dead.",
"If you can\'t turn your dreams into something real, then your imagination exists only to keep you warm.",
"Heart is like a puzzle, just fill it in wrong way and some pieces will get lost forever.",
"Curiosity opens the path of knowledge.",
"We choose today for the fate of tomorrow.",
"I feel honored to be the one who misses you!",
"What if I could share feelings, would you mind tasting someone else\'s pain?",
"Don\'t push yourself to the limit, because you\'ll need the energy to brake.",
"None of your friends could follow you down faster than me.",
"The world is always changing because people will never stay the same.",
"One person\'s choice may change the fate of thousand others.",
"Rest in peace, my dearest friend, because we\'ll be together, at the end.",
"Complicated, is a just a word, used to explain, what can\'t be explained.",
"No matter, how much you hurt yourself, think that, such pain will always be weaker than any other pain, caused by somebody else to you.",
"Why are we dreaming? Could this be, because it\'s the simplest way to keep our hope alive, or maybe it\'s our only chance to get through the madness, although you know, it\'s the righteous thing to do, when everything goes wrong.",
"Revolution is just a way of passing from madness to war.",
"Hope is everything that you have, when have nothing at all.",
"I believe you somehow, I admire you, but still, I don\'t think that you\'re right.",
"Words can\'t always to explain things, or even to make them clearer, it\'s about you to find the right answer, because it\'s in yourself.",
"People will never have a better opinion about some others than themselves.",
"Why would you care about what\'s happening around you, if you can\'t even control what\'s happening inside you.",
"One day I will see you again, even if I have to die that day.",
"One day I will find my way, but that day, it\'s just not today.",
"She\'s been here, since you first talked, she held your hand, when you first walked, she is here, even today, raise your hands, and pray her name.",
"You are mine forever, you are mine today, you are mine since always, I just think this way.",
"Imagination is the key which can unlock everything, even the impossible.",
"Even if you die, your memory might just live forever, so be careful what you do.",
"I love you since I met you, I love you still today, my love is just forever, I can\'t let you go away.",
"We don\'t need words, to speak our feelings, we don\'t need ears, to hear our beatings, we don\'t need eyes, to see our dreamings, loving each other, these are our meanings.",
"My dreams will finally become true, when I\'ll stop dreaming of you.",
"I just used to be friendly, until I got used to be alone.",
"You can prove that you are better than me so easily, without even saying it, because this is the reason why I already know it.",
"The world is full of bad people, I am not one of them, I am just part of the world.",
"You could have me at your feet, because I would be happy to stay that way.",
"You took everything away from me, everything except the memories that are haunting me, now can you just tell me, are these supposed to be a gift?",
"I know that you don\'t care of me, I just don\'t want to realize it.",
"You need to understand that I don\'t want to treat you like this, I just need to, it\'s the only way to stand your wish, and to survive your choice.",
"My future is my ending.",
"If you\'d understand my feelings, then you\'d discover my past.",
"I can\'t take it anymore, but I will take it anyhow.",
"There is no perfection in the world, because perfection is just a word with multiple meanings, one for each of us.",
"Be the person you wish to meet in this life.",
"I have killed my demons, so I can love you, but now, I don\'t know why, I\'m so alone.",
"If you share a piece of your happiness with me, I promise to share my everything with you.",
"I have lots of time to think about you, that\'s why your memory might never die.",
"Normal, it\'s a word that\'s hard to interpret, because the normal, just change it\'s meaning, day by day.",
"We are not the same, and yet the greatest of our resemblances is that, we are all different somehow.",
"You can\'t blame people for their choices, you have to let themselves feel guilty.",
"The only way to leave you behind, is to forget who I am.",
"Sometimes, I wonder if someone could ever miss me, in the way I miss you.",
"Don\'t cry for me when I\'ll be dying, because you all were laughing when I was living.",
"I don\'t need any proof, I just know you, and if I\'m wrong, I rather take disappointments from myself, for trusting my own opinions, than to admit that you lied",
"We all hide stars in our eyes, but only a few can see them, and fewer can feel them, and even less can touch them.",
"A person without cares could be considered anyhow, but dangerous.",
"We all have a different future, we all have a different past, we all cross a different way, but we may just meet sometime.",
"You will never need me, the way I need you.",
"I don\'t care what happens to my body, as long as, there\'s nothing killing my soul.",
"There will be moments, when you will be seeing things, even with your eyes shut, but that won\'t make you crazy, but just a dreamer.",
"Loneliness is peace, but too much peace is war.",
"My feelings for you grow day by day, even if you\'re not here, maybe I could find someone to give them, I can\'t stand to this my dear.",
"What would you do, when there\'s nothing that you can do, to turn your dreams into something real, when the imagination is not the key of your survival, but just the key of your revival, what if you just want to live the life that you had by now, and there\'s going to be a change that will tear everything apart in days, and you can\'t stop it, because everything that you can do, is to watch how your desires become a bunch of reasons for the person you love, to keep going further with it\'s ideal, of turning everything into ash. This is a dream, maybe a nightmare, or maybe just some words, for those who read, but not for you, because you live it now.",
"I can feel your pain, yet it is so big, if you let me, I can show you, how to handle it.",
"I am here to write about you, this is just the time, by this I meant to show you, that I won\'t to change my mind.",
"You don\'t know me, you don\'t want to know me, you don\'t really have to know me, I will just be the one who\'ll change your life.",
"We all have time to be who we want to be, but some of us, are just wasting it being who they think they are.",
"In my darkest nightmares, it just happens to be awake.",
"Being like you, might just stop me from being myself, but it could make me just perfect for you.",
"The day that never comes, is the day that never ends.",
"Don\'t laugh on anybody, you don\'t even know how much pain they took before you to meet them.",
"I wouldn\'t be able to have you, even in thousands of years, that\'s why you never really mattered.",
"I may never find you, but I will always be searching.",
"Half of me is dead, you are that half.",
"You are lost, I am lost too, but I can find myself, thinking of you.",
"Think twice before acting, because normal people, usually don\'t do that.",
"Pain it\'s useless if you can\'t learn from it.",
"I am so dead, when I\'m not dreaming.",
"Only those who have suffered in the worst ways, know how to appreciate kindness in these days.",
"Every time, when I try to fly, I hit the ground, falling from sky.",
"I have lots of things to say to you, but I just know it will waste your time.",
"I believe your lies, but I don\'t expect them to be true.",
"You can lose everything that you have by losing only one thing that you need.",
"I can be punished as hard as you like, but I won\'t let you go until the end of my life.",
"If you need to go I\'ll understand, but please just let me be your friend.",
"Each piece that remains is more important than the whole thing that it was.",
"Bad things happen to good people in most of the cases.",
"Any heart can be broken, but its feelings will remain.",
"If you could see what you mean to me, than you would know that I won\'t let go.",
"I won\'t throw my life away, I\'ll just give it to someone else.",
"Days are passing, passing it fast, memories remain, because nothing lasts.",
"You will never be apart, as long as I keep you in my mind, and I feed you from my heart.",
"I can be a fool for the rest of the world, but that\'s okay, I can live with this, as long as I\'m not the same.",
"I wish you could feel the same pain as I do when you hurt me.",
"I care for all the things that I love, so caring about you means more than you know.",
"Looking in the past it won\'t save you from the future.",
"Because no one in the end, can take you out of my head.",
"It\'s all about waiting, waiting for the end to come, and once it comes, waiting for it to finish.",
"I have never considered you an enemy, even if you always acted like one.",
"Everybody has a dark side, but this doesn\'t have to stop you from doing what\'s right.",
"There is always a way, but sometimes you just need the strength to find it.",
"I have nothing to care, when I don\'t have anything to lose.",
"You have the chance to be happy, all you need to do is hold on.",
"My dream ain\'t big, but it\'s forever, I wanna have you near, until it\'s over.",
"When excuse is not enough, apologize is your concern, you can sleep that\'s something wise, you will have so much to learn.",
"If you are not able to love your friends, then you\'ll become unable to have some.",
"No one ever knew me better, than this silky scratchy piece of paper.",
"The friends that never leave you, are not even humans.",
"You are the demon I wish I could defeat, but yet the demon I wish I could be with.",
"I live alone, I die alone, but I can\'t do it on my own.",
"I will still love you, even long after I\'ll stop believing it.",
"There are words, places and emotions from which you could never come back.",
"When I die, I will enjoy because there will be things that won\'t hurt me no more.",
"Choices are a part of you, even then when they are wrong.",
"Pleasure is not part of this life, that\'s why it comes through evil.",
"Remember the sun, because you\'ve brought the rain.",
"There are moments when you feel lost, even when you\'re going in the right way.",
"If I\'d have the wings, I wouldn\'t even fly, but covering myself in it, so you could never see me cry.",
"I have nothing to hide, but still anything to show.",
"Everything that you know about me, is just a part of the things you see.",
"World is just the place where demons have fun, while the angels suffer.",
"Love can\'t make you beautiful, but it can make you strong.",
"You seem so beautiful to me, even now after you left.",
"My head is messy and my hands are tired, but as long as my heart is beating, I will keep your soul alive.",
"The thing that I should never do, is already done.",
"You brought the rain dripping down your skin, so now don\'t wonder why you\'re getting wet.",
"One day, I wish I could tell you that, the only thing which kept me from falling was your hand.",
"What I never thought real, it was never in doubt.",
"My dream is fragile, as you know, because now you\'re here, but you always go.",
"Time is a waste, that you can\'t live without.",
"Sometimes, there is no other way to get the best, than to do the worst.",
"After all the things you\'ve thought being right, darkness is still a way to find the light.",
"If tears could speak for themselves, you would never need to talk again.",
"There are things you can\'t get by trying, only by waiting.",
"I won\'t share this feeling with anyone, because it\'s yours, and yours to come.",
"A dream can be a wish or simple thought, either way, is not about to happen, without you involving through it.",
"If for every mistake that we do, we\'d be pushed one finger into the ground, we would all die buried alive.",
"My heart is not the best place to be in, but it\'s warmer and safer than anything.",
"If she would love you, nobody would know, but if she would hated you, everyone would see.",
"I cannot tell you that I\'m okay, because you\'re not my friend, you\'re just a game.",
"I am always awake, even when I\'m dreaming.",
"You were here in front of me, I was so blind that I couldn\'t see, now you\'re so far, far away, and I think about it, day by day.",
"You are blessed by your own mentality, that\'s why my words never hurt.",
"Some dreams keep running from you, so you\'ll have to chase them.",
"The greatest knowledge about my life rests in yourself.",
"The past you choose to leave behind, may be the strongest weapon against the future.",
"If you choose to drown in your devotion, be aware of desolation.",
"Why do you pretend that there\'s nothing similar between our lives, we were made in the same way, I only chose to be different.",
"You are allowed to fall, you are allowed to scream, you are allowed to cry, but don\'t let it go, just do what is right.",
"I am complicated, but I am true, and I am here, only for you.",
"I really know what I am searching, but I don\'t know what I expect.",
"I will never leave the ones I\'ve got, even if they are not mine anymore.",
"Everyone\'s about to fall, that\'s when you need to hold them tight.",
"I\'m so sure of the place I am, and I just know where I have been, but I can\'t say where I am going.",
"I don\'t know what to say, but these words describe me the most.",
"Words are the cheapest way of killing, that\'s why your enemies are talking louder.",
"You can be whoever you want to be, but the result will never be the same.",
"I know where you are, and I know where you\'re heading, I can\'t say that I\'m happy, so I say that I accept it.",
"You could build a house from the flowers that I gave to you, but I don\'t think you\'d have the courage to live on it.",
"The fire in your heart, brings beauty to your soul.",
"I have seen a lot of bad things, so please don\'t make me see one more.",
"People are being torn apart, by the hatred from their heart.",
"You don\'t need super powers to do special things, all you need is just feelings.",
"The most valuable thing that you can give to someone, comes without a price.",
"Without you here, I have a lot of things to worry about.",
"You are the reason why I exist, so please stop treating me like this.",
"Every day spent on the earth, it\'s a day that can be worth.",
"In your mind, you can experience any thing, and it\'s so silent that, no one will ever know what you\'ve been fighting through.",
"A lot of people have to suffer, every moment of each day, and nobody cares to listen, until it reaches tragedy.",
"In orice moment al vietii tale, ma voi gandi la tine, raza de soare.",
"At least, one person could think of me all along, sad that, she lives in a story where I don\'t belong.",
"Everything\'s so simple, but you only need time to realize it.",
"Only these thoughts could keep me warm, all the time when you were gone.",
"I\'m not sure you would understand, the things that are happening inside my head.",
"I was never meant to lose you, but only to learn how to start again.",
"I have you here, near by my side, so when it hurts, I will survive.",
"Nu exista cai usoare, si cai grele, ci doar cai bune, si cai rele.",
"Maybe I will not succeed, but there is no thing to stop me from trying.",
"You will find out, what is like saving a life, when you will be the one in danger.",
"If there somewhere, an alternative reality would really be, the chance for us to exist could be reduced, because the same as we could have chosen a different path, our parents could have chosen a different path too.",
"You could be, whatever you wanted to be, but through it all. you chose to be, near beside me.",
"There is so much sadness in the world, and I don\'t understand why some people keep laughing.",
"I wish I could grab you in my arms, every time I see the stars.",
"Good or bad, things will never come as expected.",
"I wish I could learn, from the mistakes that I do, more than I learn, from all the things that I manage.",
"You are not alone, in this crazy world, we are more like you, waiting to meet each other.",
"If you don\'t want to tell me, then don\'t let me know.",
"Thank to everyone for everything they did to you, good or bad, because you couldn\'t have found the road you\'re on without them, and who knows, you could be getting much worse now.",
"You are alive now, but tell me who notice? For the world you are nothing more than just a game, that they use to play, on a rainy day.",
"There are lots of things worse than death, so I don\'t understand how people can hate it so much.",
"Only those who appreciate peace know what is like to live in a war.",
"Even at times when I was useless, you were the one who needed me most.",
"Feelings provide, secrets to hide.",
"If you would have the power to change the world, would you really care about the others?",
"There are important lessons to be learned on your own, because nobody else there would be able to teach you.",
"Maybe I can\'t touch the sky, but this won\'t stop me from chasing it.",
"There are lots of questions to be asked, about the future, about the past, and there are lots of things that should be said, to those who live, about those that\'re dead. There are lots of moments, that should be shared, with the people you keep locked inside your head, there are lots of dreams, that won\'t live forever, so chase them now, or watch them over.",
"Everybody is fighting for a purpose, and just because you don\'t know what that is, it doesn\'t mean that they should give up.",
"When it will all be over, do you think that something will still be yet to come?",
"Time is the main difference between now and tomorrow.",
"Maybe somewhere beneath the stars, there is a place that will heal these scars.",
"When we begin to fall, nobody even know, because the clouds are not important, until the rain begin to flow.",
"Do you really think of pain, when you are the one causing the sorrow?",
"If my life would be written in a song, I\'m sure that nobody would like to hear it.",
"Everybody fears of hell, because it\'s the place where demons hide, and yet nobody even care, about the misery they leave behind.",
"If God would have an opinion about each and every one of us, I wonder what would He think about me!",
"If my life would be written in scars, you name would wear the deepest.",
"The last thing she said before the war was don\'t you die, when my life depends on it.",
"I was not prepared to meet a demon so alive, and now I can\'t stop wondering, why did you let me survive.",
"We don\'t need to act in the same way, but I think that even if we would, the result will be unlike.",
"They care only about their own good, even in the times when they care about you.",
"They may not have the strongest army, but while their hearts dare to believe, it will keep them up and fighting, even when their hands will bleed.",
"No matter how many friends you would have, or how powerful would they be, there will be moments in life, when no one will be able to help you.",
"In the end, the truth won\'t matter for anyone else, but you.",
"The things that you like will show us, everyone, the kind of person that you are, because no one likes something, without desiring it.",
"If you want to start the war, then you must be ready to take the fight, you for your own self, not to push others to die for you.",
"If every tear that she has cried, would have the power to keep you alive, then you could fight through all these wars, without getting any scars.",
"No matter how many storms it will pass, a part of you will always stay the same.",
"If you already have what you desired, why don\'t you stop searching for it?",
"I listen to my demons day by day, but I never do the things they say.",
"Beneath the satisfaction of a single man, can rest the sorrow of a million others.",
"I have failed on everything that I was trying to get, but the things that I achieved through this trial, worth more now, then it would if I had succeeded in the first place.",
"I really appreciate those that are not afraid to show their ugliness to the world, because the most of them are real pretty.",
"Please come, guide me through my madness, because I feel lost, like ships in darkness.",
"See that, I am not ugly, but you just can\'t see the truth behind me.",
"If my heart would be an ocean, everyone that I know would be a wave, always struggling to leave, always heading towards the land.",
"This is the life in which I ain\'t choosing what I can do, I can only choose if I do it or not.",
"People that dream to live for thousands of years must have a real happy life, because no one can endure pain that long.",
"If we all would have been treated as equals, our world would never need to maintain a balance.",
"The right choices won\'t get you to easy ways, so don\'t be afraid when you will be crossing the hard ones.",
"There are so many people that would hate me for no reason, by just a conviction.",
"You may think that I\'m a monster, that\'s full of malice, hatred, and disgust, but yet, I am still the one that, would be throwing over a hand grenade, to save you.",
"You will always find me here, in the place you never were.",
"Kindness is the one, only and the true beauty that a person can have, anything else is just an illusion created by your senses.",
"I will be forgotten in the next day after I die, and no one will know the feelings and secrets that I hide.",
"You\'ve done so much bad to me that even my demons have come to appreciate you.",
"There are people in the world that, don\'t know how life is, therefore, they cannot appreciate anything, because they don\'t know what\'s really worth.",
"I think it\'s a mistake to want someone that much, but why am I doing this mistake?",
"When I can\'t live in peace with myself, it feels worse than if I would have lived in a war with everyone else.",
"People like you and I, they don\'t live for the entire story.",
"People like you, they are like ruins to the world, they keep standing on their feet, even after their damage has been done.",
"I am a single pixel inside the whole picture, which is the world, if I disappear no one will notice, because, there are so many others, but as it is, no one will be able to take my place, they can only make my absence unnoticed.",
"I have all the reasons in the world to hate you, but I\'m not willing to accept any of them.",
"One day, someone could miss talking to the old me, because the new me, won\'t say a goddamn word.",
"We\'ll become the victims of our own creation.",
"If humans would care about each other, as they care about themselves, the world would never live in sorrow, and no one would be hated in the end.",
"If our body and soul would share the same beauty, many of us would look like hell, because that\'s what\'s inside us, a ball of fire, waiting to burn everyone that touch us.",
"Look for me, each time when you get blinded by the dark, for the rest of the world I may not glow, but for you, I will make a spark.",
"The evil door inside me, should never be opened, so that\'s why, you only have a key for the good ones, and that\'s why, I still have secrets.",
"If you go down in hell, just trust that I will never forgive you.",
"I wish you would know that I am so simple.",
"Maybe they needed a car to feel free and run rough, but for me, having this guitar was more than enough.",
"Sometimes I wish that you could hear my thoughts, because there is nothing to be afraid of.",
"If you know that you can\'t get what you want, then you better stop wanting it anymore, because otherwise the only option is a hell inside your mind.",
"I have so many words that I never told you, and I wish you could hear them, even if they\'re said by someone else, you still deserve them.",
"I don\'t mind being judged, however the people would be, I\'m glad, because at least someone has wasted the time, thinking of me.",
"You will always be mine, even when the moon will fall, even when the sky will hide, nobody will be able, to take you out from my mind.",
"If you only let them change the world, then don\'t expect that change to please you, because satisfaction comes, only if your effort gets involved.",
"I follow a road that leads me nowhere, and all I can hope for is that you are there.",
"The people that I am close to, they don\'t even want me around.",
"The world around you, is it really there? If they\'d find you screaming, would they even care?",
"Hold on to your memories, because they will be the only proof that you once lived.",
"I don\'t want enemies, not even a single one, life already gave me enough troubles to match, and obstacles to handle, if there is something for me to do, to stop the hatred coming from you, I will do it.",
"One day, you will remember me as your greatest friend, even if today you look at me with enemy eyes, I will be there when you will need me the most, I will cure your pain, I will clear your mind, I will take your place if you will want me to.",
"If I promise you just one thing, will you let me keep my promise?",
"The world is not in my hand, and is not on my feet, because is not there supposed to be, my world is right in my arms, next to my heart, and when I hug her, she can feel, that all my feelings, they are real.",
"If my dead body could dance, would you accept an invitation?",
"You are the only person in the world, for which I would be fighting with all these years of my life again, because, only the thought of you, helped me survive it.",
"I will never win this war, in which I am fighting through, but I will never stop fighting, just as you asked me to.",
"When my life will finally end, there will be nothing left to cry for.",
"Nobody likes to be alone, so don\'t say it\'s your choice to be like that, because people like you, don\'t harm their own.",
"To be happy, you have to be selfish, because no one will give you happiness, unless you take it by yourself.",
"We are like two different storms that come together under the same blue sky.",
"Life is like a rain in which we\'re all the raindrops, falling from the same cloud, hitting the same ground, but just in different places and at a different time. Some of us will choose to feed flowers, others will choose to feed trees, and some will simply choose to dig holes into the dry land. But, in the end, it\'s not our life that truly matter, but the things we do with it.",
"Do you know how many people out there, don\'t even know about your existence?",
"If I would have to choose to be the idiot, I would choose to be the goddamn good one.",
"People that don\'t fight for what is theirs, will come to have nothing for themselves.",
"Everybody knows a different version of me, some of them think that I am bad, just because I\'ve been seen hitting other person, some of them think that I am good, just because I\'ve been seen helping other person, some of them think that I am ugly, just because I\'ve been seen with my hair messed up, but there is no one to know the real me, the reason for all this, as the entire story.",
"You are not worried about my life, because it\'s yours that it\'s important.",
"Physically, you hear the same sounds as I do, but they are not saying the same thing to your mind, because you process them differently.",
"You don\'t need to struggle yourself that much, only to be the loved one, because in the end, people will find reasons to hate you, anyhow.",
];
function grabRandomQuote () {
	var length = quote_list.length;
	var choice = Math.floor(Math.random()*length);
	document.getElementById("quote_window").innerHTML = quote_list[choice];
	document.getElementById("quote_length").innerHTML = "No of characters: " + quote_list[choice].length;
	if(choice%10 == 0) {document.getElementById("quote_window").style.backgroundColor = "#7FFF00";} //color green
	else if(choice%10 == 1) {document.getElementById("quote_window").style.backgroundColor = "#20B2AA";} // color light sea blue
	else if(choice%10 == 2) {document.getElementById("quote_window").style.backgroundColor = "#FF6347";} //color tomato
	else if(choice%10 == 3) {document.getElementById("quote_window").style.backgroundColor = "#F0E68C";} //color khaki
	else if(choice%10 == 4) {document.getElementById("quote_window").style.backgroundColor = "#FFA07A";} //color light salmon
	else if(choice%10 == 5) {document.getElementById("quote_window").style.backgroundColor = "#ADD8E6";} //color light blue
	else if(choice%10 == 6) {document.getElementById("quote_window").style.backgroundColor = "#D3D3D3";} //color light gray
	else if(choice%10 == 7) {document.getElementById("quote_window").style.backgroundColor = "#8FBC8F";} //color dark sea green
	else if(choice%10 == 8) {document.getElementById("quote_window").style.backgroundColor = "#FFB6C1";} //color light pink
	else if(choice%10 == 9) {document.getElementById("quote_window").style.backgroundColor = "#FF7F50";} //color  coral orange
 };