name: Dispatch Update Submodule
on:
  push:
    branches:
      - master
jobs:
  dispatch:
    steps:
      - name: Dispatch update to Git Referenced Submodules
        uses: dragos.vacariu/portofolio
        with:
          repository: dragos.vacariu/portofolio
          event-type: update-submodule